// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSDlgW3PdIVK8hBVq5ml2KLPuIhbtTUg',
    appId: '1:423818050881:web:dcf3df21c57cf5a69d35c0',
    messagingSenderId: '423818050881',
    projectId: 'loginappusingphone',
    authDomain: 'loginappusingphone.firebaseapp.com',
    storageBucket: 'loginappusingphone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7_NFMwDpwy1zzwD5WHII62Gp-uIQQLI',
    appId: '1:423818050881:android:c10abcdf24397cb59d35c0',
    messagingSenderId: '423818050881',
    projectId: 'loginappusingphone',
    storageBucket: 'loginappusingphone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmwwgDyHb8cAO0hGZ73E2rJU2JOn9EGw',
    appId: '1:423818050881:ios:d861155734e1dc1f9d35c0',
    messagingSenderId: '423818050881',
    projectId: 'loginappusingphone',
    storageBucket: 'loginappusingphone.appspot.com',
    iosBundleId: 'com.example.loginUsingPhoneV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUmwwgDyHb8cAO0hGZ73E2rJU2JOn9EGw',
    appId: '1:423818050881:ios:d861155734e1dc1f9d35c0',
    messagingSenderId: '423818050881',
    projectId: 'loginappusingphone',
    storageBucket: 'loginappusingphone.appspot.com',
    iosBundleId: 'com.example.loginUsingPhoneV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRSDlgW3PdIVK8hBVq5ml2KLPuIhbtTUg',
    appId: '1:423818050881:web:e285380a5735225b9d35c0',
    messagingSenderId: '423818050881',
    projectId: 'loginappusingphone',
    authDomain: 'loginappusingphone.firebaseapp.com',
    storageBucket: 'loginappusingphone.appspot.com',
  );
}
